//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UhaSub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UhaSub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sub is developed as a alternative for popsub.
        ///It&apos;s an open-source software.
        ///For more information, please see http://github.com/doolb/UhaSub
        ///.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutSetting {
            get {
                return ResourceManager.GetString("AboutSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go after 3 sec.
        /// </summary>
        public static string cfg_key_go_after {
            get {
                return ResourceManager.GetString("cfg_key_go_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go before 3 sec.
        /// </summary>
        public static string cfg_key_go_before {
            get {
                return ResourceManager.GetString("cfg_key_go_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or Pause.
        /// </summary>
        public static string cfg_key_play_pause {
            get {
                return ResourceManager.GetString("cfg_key_play_pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control sub.
        /// </summary>
        public static string cfg_key_sub {
            get {
                return ResourceManager.GetString("cfg_key_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set end time.
        /// </summary>
        public static string cfg_key_sub_end {
            get {
                return ResourceManager.GetString("cfg_key_sub_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save sub.
        /// </summary>
        public static string cfg_key_sub_save {
            get {
                return ResourceManager.GetString("cfg_key_sub_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set start time.
        /// </summary>
        public static string cfg_key_sub_start {
            get {
                return ResourceManager.GetString("cfg_key_sub_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to set start time
        ///release to set end time.
        /// </summary>
        public static string cfg_key_sub_time {
            get {
                return ResourceManager.GetString("cfg_key_sub_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control video.
        /// </summary>
        public static string cfg_key_video {
            get {
                return ResourceManager.GetString("cfg_key_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End delay time.
        /// </summary>
        public static string cfg_sub_end {
            get {
                return ResourceManager.GetString("cfg_sub_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start delay time.
        /// </summary>
        public static string cfg_sub_start {
            get {
                return ResourceManager.GetString("cfg_sub_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string cfg_ui_lang {
            get {
                return ResourceManager.GetString("cfg_ui_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language need restart..
        /// </summary>
        public static string cfg_ui_lang_change {
            get {
                return ResourceManager.GetString("cfg_ui_lang_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string cfg_ui_text {
            get {
                return ResourceManager.GetString("cfg_ui_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string cfg_ui_theme {
            get {
                return ResourceManager.GetString("cfg_ui_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry  we could load this file,please select *.txt or *.ass..
        /// </summary>
        public static string FileNoSupport {
            get {
                return ResourceManager.GetString("FileNoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keyboard setting.
        /// </summary>
        public static string KeySetting {
            get {
                return ResourceManager.GetString("KeySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sub.
        /// </summary>
        public static string on_save {
            get {
                return ResourceManager.GetString("on_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sub to another file.
        /// </summary>
        public static string on_save_as {
            get {
                return ResourceManager.GetString("on_save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open video file
        ///and try to open relational ass file .
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change setting.
        /// </summary>
        public static string OpenSetting {
            get {
                return ResourceManager.GetString("OpenSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a sub file 
        ///(txt,ass).
        /// </summary>
        public static string OpenSub {
            get {
                return ResourceManager.GetString("OpenSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string sub_head_end {
            get {
                return ResourceManager.GetString("sub_head_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string sub_head_start {
            get {
                return ResourceManager.GetString("sub_head_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string sub_head_text {
            get {
                return ResourceManager.GetString("sub_head_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success!.
        /// </summary>
        public static string sub_save_success {
            get {
                return ResourceManager.GetString("sub_save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we can&apos;t open sub file for this video,
        ///Please select a sub file..
        /// </summary>
        public static string SubFileNoFound {
            get {
                return ResourceManager.GetString("SubFileNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub setting.
        /// </summary>
        public static string SubSetting {
            get {
                return ResourceManager.GetString("SubSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UhaSub.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user interface setting.
        /// </summary>
        public static string UISetting {
            get {
                return ResourceManager.GetString("UISetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutex.
        /// </summary>
        public static string video_mutex_tip {
            get {
                return ResourceManager.GetString("video_mutex_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutex Off.
        /// </summary>
        public static string video_nomutex_tip {
            get {
                return ResourceManager.GetString("video_nomutex_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string video_pause_tip {
            get {
                return ResourceManager.GetString("video_pause_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string video_play_tip {
            get {
                return ResourceManager.GetString("video_play_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Preview.
        /// </summary>
        public static string video_sub_preview {
            get {
                return ResourceManager.GetString("video_sub_preview", resourceCulture);
            }
        }
    }
}
